name: Client CI

on:
  push:
    branches: [master, 'release/**']
  pull_request:
    branches: [master, 'release/**']
  workflow_dispatch:
    inputs:
      run_e2e:
        description: 'Run E2E tests'
        required: false
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  checks:
    uses: revisium/revisium-actions/.github/workflows/node-build.yml@763f2746000f15842e642130dba3acf09c5d00ac # v0.3.2
    with:
      node_version: 24.11.1
      install_command: npm ci
      run_commands: |
        npm run ts:check
        npm run lint
        npm run test:ci

  sonar:
    needs: checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  e2e:
    if: github.event_name == 'workflow_dispatch' && inputs.run_e2e
    uses: revisium/revisium-actions/.github/workflows/node-build.yml@763f2746000f15842e642130dba3acf09c5d00ac # v0.3.2
    with:
      node_version: 24.11.1
      install_command: npm ci
      run_commands: |
        ./node_modules/.bin/playwright install --with-deps chromium
        npm run test:e2e
